# url: jdbc:sqlserver://mssqldev.cr24o06285ta.ap-south-1.rds.amazonaws.com;databaseName=liquibase;encrypt=true;trustServerCertificate=true;
# username: adminuser
# password: MySecurePassword123!

# defaultSchemaName: dbo
# liquibaseSchemaName: dbo

url: jdbc:sqlserver://localhost;databaseName=master;encrypt=true;trustServerCertificate=true;
username: sa
password: YourStrong@Password123
liquibase.liquibaseCatalogName=master
liquibase.liquibaseSchemaName=dbo
