--liquibase formatted sql

--changeset Day2_Create_Role:ReadOnly-Role runOnChange:true runWith:sqlplus
--comment:Create Read Only Role

CREATE ROLE READ_ONLY NOT IDENTIFIED;

GRANT EXECUTE ANY ASSEMBLY TO READ_ONLY;
GRANT EXECUTE ANY CLASS TO READ_ONLY;
GRANT EXECUTE ANY INDEXTYPE TO READ_ONLY;
GRANT EXECUTE ANY LIBRARY TO READ_ONLY;
GRANT EXECUTE ANY OPERATOR TO READ_ONLY;
GRANT EXECUTE ANY PROCEDURE TO READ_ONLY;
GRANT EXECUTE ANY PROGRAM TO READ_ONLY;
GRANT EXECUTE ANY TYPE TO READ_ONLY;
GRANT EXECUTE ASSEMBLY TO READ_ONLY;
GRANT SELECT ANY CUBE TO READ_ONLY;
GRANT SELECT ANY CUBE DIMENSION TO READ_ONLY;
GRANT SELECT ANY MINING MODEL TO READ_ONLY;
GRANT SELECT ANY SEQUENCE TO READ_ONLY;
GRANT SELECT ANY TABLE TO READ_ONLY;
GRANT SELECT ANY TRANSACTION TO READ_ONLY;
GRANT SELECT_CATALOG_ROLE TO READ_ONLY;
GRANT SELECT ANY DICTIONARY TO READ_ONLY;

--rollback DROP ROLE READ_ONLY;

--------------------------------------------------------------------------------

--changeset Day2_Create_Role:ReadWrite-Role runOnChange:true runWith:sqlplus
--comment:Create Read Write Role

CREATE ROLE READ_WRITE NOT IDENTIFIED;

GRANT ALTER ANY TABLE TO READ_WRITE;
GRANT ALTER ANY INDEX TO READ_WRITE;
GRANT ALTER ANY INDEXTYPE TO READ_WRITE;
GRANT ALTER ANY LIBRARY TO READ_WRITE;
GRANT ALTER ANY MATERIALIZED VIEW TO READ_WRITE;
GRANT ALTER ANY PROCEDURE TO READ_WRITE;
GRANT ALTER ANY SEQUENCE TO READ_WRITE;
GRANT ALTER ANY TABLE TO READ_WRITE;
GRANT ALTER ANY TRIGGER TO READ_WRITE;
GRANT DEBUG ANY PROCEDURE TO READ_WRITE;
GRANT EXECUTE ANY ASSEMBLY TO READ_WRITE;
GRANT EXECUTE ANY CLASS TO READ_WRITE;
GRANT EXECUTE ANY INDEXTYPE TO READ_WRITE;
GRANT EXECUTE ANY LIBRARY TO READ_WRITE;
GRANT EXECUTE ANY OPERATOR TO READ_WRITE;
GRANT EXECUTE ANY PROCEDURE TO READ_WRITE;
GRANT EXECUTE ANY PROGRAM TO READ_WRITE;
GRANT CREATE ANY TABLE TO READ_WRITE;
GRANT CREATE ANY VIEW TO READ_WRITE;
GRANT CREATE ANY PROCEDURE TO READ_WRITE;
GRANT CREATE ANY SEQUENCE TO READ_WRITE;
GRANT SELECT ANY TABLE TO READ_WRITE;
GRANT INSERT ANY TABLE TO READ_WRITE;
GRANT UPDATE ANY TABLE TO READ_WRITE;
GRANT DELETE ANY TABLE TO READ_WRITE;
GRANT CREATE ANY INDEX,DROP ANY INDEX TO READ_WRITE;
GRANT DROP ANY TABLE TO READ_WRITE;

--rollback drop role READ_WRITE;

--------------------------------------------------------------------------------

--changeset day2_create_role:BigID-Role runonchange:true runwith:sqlplus
--comment:create BigID User role

CREATE ROLE ${BIGID_ROLE} NOT IDENTIFIED;

GRANT CREATE SESSION TO ${BIGID_ROLE};
GRANT SELECT ON DBA_AUDIT_TRAIL TO ${BIGID_ROLE};
GRANT READ ANY TABLE TO ${BIGID_ROLE};

--rollback DROP ROLE ${BIGID_ROLE};

--------------------------------------------------------------------------------

--changeset day2_create_role:DARE-Role runonchange:true runwith:sqlplus
--comment:create DARE Team role

CREATE ROLE ${DARE_ROLE} NOT IDENTIFIED;

GRANT ALTER SESSION TO ${DARE_ROLE};
GRANT CREATE CLUSTER TO ${DARE_ROLE};
GRANT CREATE DATABASE LINK TO ${DARE_ROLE};
GRANT CREATE PUBLIC SYNONYM TO ${DARE_ROLE};
GRANT CREATE SEQUENCE TO ${DARE_ROLE};
GRANT CREATE SESSION TO ${DARE_ROLE};
GRANT CREATE SYNONYM TO ${DARE_ROLE};
GRANT CREATE TABLE TO ${DARE_ROLE};
GRANT CREATE TRIGGER TO ${DARE_ROLE};
GRANT CREATE VIEW TO ${DARE_ROLE};
GRANT ALTER ANY TABLE TO ${DARE_ROLE};
GRANT DROP ANY TABLE TO ${DARE_ROLE};
GRANT CREATE INDEXTYPE TO ${DARE_ROLE};
GRANT CREATE PROCEDURE TO ${DARE_ROLE};
GRANT CREATE TYPE TO ${DARE_ROLE};

GRANT ADMINISTER ANY SQL TUNING SET TO ${DARE_ROLE};
GRANT ADMINISTER DATABASE TRIGGER TO ${DARE_ROLE};
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO ${DARE_ROLE};
GRANT ADMINISTER SQL TUNING SET TO ${DARE_ROLE};
GRANT ADVISOR TO ${DARE_ROLE};
GRANT ALTER ANY ASSEMBLY TO ${DARE_ROLE};
GRANT ALTER ANY CLUSTER TO ${DARE_ROLE};
GRANT ALTER ANY CUBE TO ${DARE_ROLE};
GRANT ALTER ANY CUBE DIMENSION TO ${DARE_ROLE};
GRANT ALTER ANY DIMENSION TO ${DARE_ROLE};
GRANT ALTER ANY EDITION TO ${DARE_ROLE};
GRANT ALTER ANY INDEX TO ${DARE_ROLE};
GRANT ALTER ANY INDEXTYPE TO ${DARE_ROLE};
GRANT ALTER ANY LIBRARY TO ${DARE_ROLE};
GRANT ALTER ANY MATERIALIZED VIEW TO ${DARE_ROLE};
GRANT ALTER ANY MINING MODEL TO ${DARE_ROLE};
GRANT ALTER ANY OPERATOR TO ${DARE_ROLE};
GRANT ALTER ANY OUTLINE TO ${DARE_ROLE};
GRANT ALTER ANY PROCEDURE TO ${DARE_ROLE};
GRANT ALTER ANY ROLE TO ${DARE_ROLE};
GRANT ALTER ANY SEQUENCE TO ${DARE_ROLE};
GRANT ALTER ANY SQL PROFILE TO ${DARE_ROLE};
GRANT ALTER ANY SQL TRANSLATION PROFILE TO ${DARE_ROLE};
GRANT ALTER ANY TABLE TO ${DARE_ROLE};
GRANT ALTER ANY TRIGGER TO ${DARE_ROLE};
GRANT ALTER ANY TYPE TO ${DARE_ROLE};
GRANT ALTER PROFILE TO ${DARE_ROLE};
GRANT ALTER RESOURCE COST TO ${DARE_ROLE};
GRANT ALTER ROLLBACK SEGMENT TO ${DARE_ROLE};
GRANT ALTER SESSION TO ${DARE_ROLE};
GRANT ALTER TABLESPACE TO ${DARE_ROLE};
GRANT ALTER USER TO ${DARE_ROLE};
GRANT ANALYZE ANY TO ${DARE_ROLE};
GRANT AUDIT ANY TO ${DARE_ROLE};
GRANT AUDIT SYSTEM TO ${DARE_ROLE};
GRANT BACKUP ANY TABLE TO ${DARE_ROLE};
GRANT BECOME USER TO ${DARE_ROLE};
GRANT CHANGE NOTIFICATION TO ${DARE_ROLE};
GRANT COMMENT ANY MINING MODEL TO ${DARE_ROLE};
GRANT COMMENT ANY TABLE TO ${DARE_ROLE};
GRANT CREATE ANY ASSEMBLY TO ${DARE_ROLE};
GRANT CREATE ANY CLUSTER TO ${DARE_ROLE};
GRANT CREATE ANY CONTEXT TO ${DARE_ROLE};
GRANT CREATE ANY CUBE TO ${DARE_ROLE};
GRANT CREATE ANY CUBE BUILD PROCESS TO ${DARE_ROLE};
GRANT CREATE ANY CUBE DIMENSION TO ${DARE_ROLE};
GRANT CREATE ANY DIMENSION TO ${DARE_ROLE};
GRANT CREATE ANY EDITION TO ${DARE_ROLE};
GRANT CREATE ANY INDEX TO ${DARE_ROLE};
GRANT CREATE ANY INDEXTYPE TO ${DARE_ROLE};
GRANT CREATE ANY JOB TO ${DARE_ROLE};
GRANT CREATE ANY LIBRARY TO ${DARE_ROLE};
GRANT CREATE ANY MATERIALIZED VIEW TO ${DARE_ROLE};
GRANT CREATE ANY MEASURE FOLDER TO ${DARE_ROLE};
GRANT CREATE ANY MINING MODEL TO ${DARE_ROLE};
GRANT CREATE ANY OPERATOR TO ${DARE_ROLE};
GRANT CREATE ANY OUTLINE TO ${DARE_ROLE};
GRANT CREATE ANY PROCEDURE TO ${DARE_ROLE};
GRANT CREATE ANY SEQUENCE TO ${DARE_ROLE};
GRANT CREATE ANY SQL PROFILE TO ${DARE_ROLE};
GRANT CREATE ANY SQL TRANSLATION PROFILE TO ${DARE_ROLE};
GRANT CREATE ANY SYNONYM TO ${DARE_ROLE};
GRANT CREATE ANY TABLE TO ${DARE_ROLE};
GRANT CREATE ANY TRIGGER TO ${DARE_ROLE};
GRANT CREATE ANY TYPE TO ${DARE_ROLE};
GRANT CREATE ANY VIEW TO ${DARE_ROLE};
GRANT CREATE ASSEMBLY TO ${DARE_ROLE};
GRANT CREATE CLUSTER TO ${DARE_ROLE};
GRANT CREATE CUBE TO ${DARE_ROLE};
GRANT CREATE CUBE BUILD PROCESS TO ${DARE_ROLE};
GRANT CREATE CUBE DIMENSION TO ${DARE_ROLE};
GRANT CREATE DATABASE LINK TO ${DARE_ROLE};
GRANT CREATE DIMENSION TO ${DARE_ROLE};
GRANT CREATE INDEXTYPE TO ${DARE_ROLE};
GRANT CREATE JOB TO ${DARE_ROLE};
GRANT CREATE LIBRARY TO ${DARE_ROLE};
GRANT CREATE MATERIALIZED VIEW TO ${DARE_ROLE};
GRANT CREATE MEASURE FOLDER TO ${DARE_ROLE};
GRANT CREATE MINING MODEL TO ${DARE_ROLE};
GRANT CREATE OPERATOR TO ${DARE_ROLE};
GRANT CREATE PROCEDURE TO ${DARE_ROLE};
GRANT CREATE PROFILE TO ${DARE_ROLE};
GRANT CREATE PUBLIC DATABASE LINK TO ${DARE_ROLE};
GRANT CREATE PUBLIC SYNONYM TO ${DARE_ROLE};
GRANT CREATE ROLE TO ${DARE_ROLE};
GRANT CREATE ROLLBACK SEGMENT TO ${DARE_ROLE};
GRANT CREATE SEQUENCE TO ${DARE_ROLE};
GRANT CREATE SESSION TO ${DARE_ROLE};
GRANT CREATE SQL TRANSLATION PROFILE TO ${DARE_ROLE};
GRANT CREATE SYNONYM TO ${DARE_ROLE};
GRANT CREATE TABLE TO ${DARE_ROLE};
GRANT CREATE TABLESPACE TO ${DARE_ROLE};
GRANT CREATE TRIGGER TO ${DARE_ROLE};
GRANT CREATE TYPE TO ${DARE_ROLE};
GRANT CREATE USER TO ${DARE_ROLE};
GRANT CREATE VIEW TO ${DARE_ROLE};
GRANT DEBUG ANY PROCEDURE TO ${DARE_ROLE};
GRANT DEBUG CONNECT SESSION TO ${DARE_ROLE};
GRANT DELETE ANY CUBE DIMENSION TO ${DARE_ROLE};
GRANT DELETE ANY MEASURE FOLDER TO ${DARE_ROLE};
GRANT DELETE ANY TABLE TO ${DARE_ROLE};
GRANT DROP ANY ASSEMBLY TO ${DARE_ROLE};
GRANT DROP ANY CLUSTER TO ${DARE_ROLE};
GRANT DROP ANY CONTEXT TO ${DARE_ROLE};
GRANT DROP ANY CUBE TO ${DARE_ROLE};
GRANT DROP ANY CUBE BUILD PROCESS TO ${DARE_ROLE};
GRANT DROP ANY CUBE DIMENSION TO ${DARE_ROLE};
GRANT DROP ANY DIMENSION TO ${DARE_ROLE};
GRANT DROP ANY DIRECTORY TO ${DARE_ROLE};
GRANT DROP ANY EDITION TO ${DARE_ROLE};
GRANT DROP ANY INDEX TO ${DARE_ROLE};
GRANT DROP ANY INDEXTYPE TO ${DARE_ROLE};
GRANT DROP ANY LIBRARY TO ${DARE_ROLE};
GRANT DROP ANY MATERIALIZED VIEW TO ${DARE_ROLE};
GRANT DROP ANY MEASURE FOLDER TO ${DARE_ROLE};
GRANT DROP ANY MINING MODEL TO ${DARE_ROLE};
GRANT DROP ANY OPERATOR TO ${DARE_ROLE};
GRANT DROP ANY OUTLINE TO ${DARE_ROLE};
GRANT DROP ANY PROCEDURE TO ${DARE_ROLE};
GRANT DROP ANY ROLE TO ${DARE_ROLE};
GRANT DROP ANY SEQUENCE TO ${DARE_ROLE};
GRANT DROP ANY SQL PROFILE TO ${DARE_ROLE};
GRANT DROP ANY SQL TRANSLATION PROFILE TO ${DARE_ROLE};
GRANT DROP ANY SYNONYM TO ${DARE_ROLE};
GRANT DROP ANY TABLE TO ${DARE_ROLE};
GRANT DROP ANY TRIGGER TO ${DARE_ROLE};
GRANT DROP ANY TYPE TO ${DARE_ROLE};
GRANT DROP ANY VIEW TO ${DARE_ROLE};
GRANT DROP PROFILE TO ${DARE_ROLE};
GRANT DROP PUBLIC DATABASE LINK TO ${DARE_ROLE};
GRANT DROP PUBLIC SYNONYM TO ${DARE_ROLE};
GRANT DROP ROLLBACK SEGMENT TO ${DARE_ROLE};
GRANT DROP TABLESPACE TO ${DARE_ROLE};
GRANT DROP USER TO ${DARE_ROLE};
GRANT EM EXPRESS CONNECT TO ${DARE_ROLE};
GRANT EXECUTE ANY ASSEMBLY TO ${DARE_ROLE};
GRANT EXECUTE ANY CLASS TO ${DARE_ROLE};
GRANT EXECUTE ANY INDEXTYPE TO ${DARE_ROLE};
GRANT EXECUTE ANY LIBRARY TO ${DARE_ROLE};
GRANT EXECUTE ANY OPERATOR TO ${DARE_ROLE};
GRANT EXECUTE ANY PROCEDURE TO ${DARE_ROLE};
GRANT EXECUTE ANY PROGRAM TO ${DARE_ROLE};
GRANT EXECUTE ANY TYPE TO ${DARE_ROLE};
GRANT EXECUTE ASSEMBLY TO ${DARE_ROLE};
GRANT EXPORT FULL DATABASE TO ${DARE_ROLE};
GRANT FLASHBACK ANY TABLE TO ${DARE_ROLE};
GRANT FLASHBACK ARCHIVE ADMINISTER TO ${DARE_ROLE};
GRANT FORCE ANY TRANSACTION TO ${DARE_ROLE};
GRANT FORCE TRANSACTION TO ${DARE_ROLE};
GRANT GLOBAL QUERY REWRITE TO ${DARE_ROLE};
GRANT GRANT ANY OBJECT PRIVILEGE TO ${DARE_ROLE};
GRANT IMPORT FULL DATABASE TO ${DARE_ROLE};
GRANT INSERT ANY CUBE DIMENSION TO ${DARE_ROLE};
GRANT INSERT ANY MEASURE FOLDER TO ${DARE_ROLE};
GRANT INSERT ANY TABLE TO ${DARE_ROLE};
GRANT LOCK ANY TABLE TO ${DARE_ROLE};
GRANT MANAGE SCHEDULER TO ${DARE_ROLE};
GRANT MANAGE TABLESPACE TO ${DARE_ROLE};
GRANT MERGE ANY VIEW TO ${DARE_ROLE};
GRANT ON COMMIT REFRESH TO ${DARE_ROLE};
GRANT QUERY REWRITE TO ${DARE_ROLE};
GRANT REDEFINE ANY TABLE TO ${DARE_ROLE};
GRANT RESTRICTED SESSION TO ${DARE_ROLE};
GRANT RESUMABLE TO ${DARE_ROLE};
GRANT SELECT ANY CUBE TO ${DARE_ROLE};
GRANT SELECT ANY CUBE DIMENSION TO ${DARE_ROLE};
GRANT SELECT ANY MINING MODEL TO ${DARE_ROLE};
GRANT SELECT ANY SEQUENCE TO ${DARE_ROLE};
GRANT SELECT ANY TABLE TO ${DARE_ROLE};
GRANT SELECT ANY TRANSACTION TO ${DARE_ROLE};
GRANT UNDER ANY TABLE TO ${DARE_ROLE};
GRANT UNDER ANY TYPE TO ${DARE_ROLE};
GRANT UNDER ANY VIEW TO ${DARE_ROLE};
GRANT UPDATE ANY CUBE TO ${DARE_ROLE};
GRANT UPDATE ANY CUBE BUILD PROCESS TO ${DARE_ROLE};
GRANT UPDATE ANY CUBE DIMENSION TO ${DARE_ROLE};
GRANT UPDATE ANY TABLE TO ${DARE_ROLE};
GRANT USE ANY SQL TRANSLATION PROFILE TO ${DARE_ROLE};
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO ${DARE_ROLE};
GRANT SELECT_CATALOG_ROLE TO ${DARE_ROLE};
GRANT SELECT ANY DICTIONARY TO ${DARE_ROLE};

--rollback DROP ROLE ${DARE_ROLE};