--liquibase formatted sql

--changeset Day2_Create_Profile:APPS_USER-Profile runOnChange:true runWith:sqlplus
--comment:Create APPS_USER Profile

CREATE PROFILE "APPS_USER"
    LIMIT
        COMPOSITE_LIMIT DEFAULT
        SESSIONS_PER_USER DEFAULT
        CPU_PER_SESSION DEFAULT
        CPU_PER_CALL DEFAULT
        LOGICAL_READS_PER_SESSION DEFAULT
        LOGICAL_READS_PER_CALL DEFAULT
        IDLE_TIME DEFAULT
        CONNECT_TIME DEFAULT
        PRIVATE_SGA DEFAULT
        FAILED_LOGIN_ATTEMPTS 6
        PASSWORD_LIFE_TIME UNLIMITED
        PASSWORD_REUSE_TIME UNLIMITED
        PASSWORD_REUSE_MAX 10
        PASSWORD_VERIFY_FUNCTION "PASSWORD_COMPLEXITY_FUNCTION"
        PASSWORD_LOCK_TIME UNLIMITED
        PASSWORD_GRACE_TIME UNLIMITED
        INACTIVE_ACCOUNT_TIME DEFAULT
        PASSWORD_ROLLOVER_TIME DEFAULT;

--rollback DROP PROFILE "APPS_USER";

-------------------------------------------------------------------------------------------------
--changeset Day2_Create_Profile:END_USER-Profile runOnChange:true runWith:sqlplus
--comment:Create END_USER Profile

CREATE PROFILE "END_USER"
    LIMIT
        COMPOSITE_LIMIT DEFAULT
        SESSIONS_PER_USER DEFAULT
        CPU_PER_SESSION DEFAULT
        CPU_PER_CALL DEFAULT
        LOGICAL_READS_PER_SESSION DEFAULT
        LOGICAL_READS_PER_CALL DEFAULT
        IDLE_TIME DEFAULT
        CONNECT_TIME DEFAULT
        PRIVATE_SGA DEFAULT
        FAILED_LOGIN_ATTEMPTS 6
        PASSWORD_LIFE_TIME 90
        PASSWORD_REUSE_TIME UNLIMITED
        PASSWORD_REUSE_MAX 10
        PASSWORD_VERIFY_FUNCTION "PASSWORD_COMPLEXITY_FUNCTION"
        PASSWORD_LOCK_TIME UNLIMITED
        PASSWORD_GRACE_TIME 5
        INACTIVE_ACCOUNT_TIME DEFAULT
        PASSWORD_ROLLOVER_TIME DEFAULT;

--rollback DROP PROFILE "END_USER";