--liquibase formatted sql

--changeset Day2_Create_Role:APP-RW-${SCHEMA_NAME}-ROLE runOnChange:true
--comment:Create schema specific App Read Write Role
${SCHEMA_ROLE};

SET ROLE ${DEPLOY_ROLE};
CREATE ROLE ${APP_RW_ROLE};
RESET ROLE;
GRANT CONNECT, TEMPORARY ON DATABASE ${DB_NAME} TO ${APP_RW_ROLE};
GRANT USAGE, CREATE ON SCHEMA ${SCHEMA_NAME} TO ${APP_RW_ROLE};
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA ${SCHEMA_NAME} TO ${APP_RW_ROLE};
GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA ${SCHEMA_NAME} TO ${APP_RW_ROLE};
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ${SCHEMA_NAME} TO ${APP_RW_ROLE};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO ${APP_RW_ROLE};
ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} GRANT SELECT, USAGE ON SEQUENCES TO ${APP_RW_ROLE};
ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} GRANT EXECUTE ON FUNCTIONS TO ${APP_RW_ROLE};

GRANT ${APP_RW_ROLE} TO ${APP_RW_USER};

--rollback ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} REVOKE ALL ON TABLES FROM ${APP_RW_ROLE};
--rollback ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} REVOKE ALL ON SEQUENCES FROM ${APP_RW_ROLE};
--rollback ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} REVOKE ALL ON FUNCTIONS FROM ${APP_RW_ROLE};
--rollback REVOKE ALL ON SCHEMA ${SCHEMA_NAME} FROM ${APP_RW_ROLE};
--rollback REVOKE ALL ON DATABASE ${DB_NAME} FROM ${APP_RW_ROLE};
--rollback DROP ROLE ${APP_RW_ROLE};

--------------------------------------------------------------------------------

--changeset Day2_Create_Role:APP-RO-${SCHEMA_NAME}-ROLE runOnChange:true
--comment:Create schema specific App Read Only Role
${SCHEMA_ROLE};

SET ROLE ${DEPLOY_ROLE};
CREATE ROLE ${APP_RO_ROLE};
RESET ROLE;

GRANT CONNECT ON DATABASE ${DB_NAME} TO ${APP_RO_ROLE};
GRANT USAGE ON SCHEMA ${SCHEMA_NAME} TO ${APP_RO_ROLE};
GRANT SELECT ON ALL TABLES IN SCHEMA ${SCHEMA_NAME} TO ${APP_RO_ROLE};
GRANT SELECT ON ALL SEQUENCES IN SCHEMA ${SCHEMA_NAME} TO ${APP_RO_ROLE};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} GRANT SELECT ON TABLES TO ${APP_RO_ROLE};
ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} GRANT SELECT ON SEQUENCES TO ${APP_RO_ROLE};

GRANT ${APP_RO_ROLE} TO ${APP_RO_USER};

--rollback ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} REVOKE ALL ON TABLES FROM ${APP_RO_ROLE};
--rollback ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} REVOKE ALL ON SEQUENCES FROM ${APP_RO_ROLE};
--rollback REVOKE ALL ON SCHEMA ${SCHEMA_NAME} FROM ${APP_RO_ROLE};
--rollback REVOKE ALL ON DATABASE ${DB_NAME} FROM ${APP_RO_ROLE};
--rollback DROP ROLE ${APP_RO_ROLE};

--------------------------------------------------------------------------------

--changeset Day2_Create_Role:DEPLOY-${SCHEMA}-ROLE runOnChange:true
--comment:Grant schema specific permissions to Deploy Role

GRANT USAGE, CREATE ON SCHEMA ${SCHEMA_NAME} TO ${DEPLOY_ROLE};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ${SCHEMA_NAME} TO ${DEPLOY_ROLE};
GRANT SELECT, USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA ${SCHEMA_NAME} TO ${DEPLOY_ROLE};
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ${SCHEMA_NAME} TO ${DEPLOY_ROLE};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DEPLOY_ROLE};
ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} GRANT SELECT, USAGE, UPDATE ON SEQUENCES TO ${DEPLOY_ROLE};
ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} GRANT EXECUTE ON FUNCTIONS TO ${DEPLOY_ROLE};

ALTER SCHEMA ${SCHEMA_NAME} OWNER TO ${APP_LIQUIBASE_USER};

--rollback ALTER SCHEMA ${SCHEMA_NAME} OWNER TO ${master_user};
--rollback ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} REVOKE ALL ON TABLES FROM ${DEPLOY_ROLE};
--rollback ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} REVOKE ALL ON SEQUENCES FROM ${DEPLOY_ROLE};
--rollback ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} REVOKE ALL ON FUNCTIONS FROM ${DEPLOY_ROLE};
--rollback REVOKE ALL ON SCHEMA ${SCHEMA_NAME} FROM ${DEPLOY_ROLE};