url: jdbc:postgresql://${endpoint}:${port}/${DB_NAME}
username: ${master_user}
password: ${master_pass}
logLevel: info
vault.addr: ${DBA_VAULT_ADDR}
vault.namespace: ${DBA_VAULT_NAMESPACE}
vault.token: ${DBA_VAULT_TOKEN}

liquibase.liquibaseSchemaName: ${DEFAULT_SCHEMA}