url: jdbc:oracle:thin:@${endpoint}:${port}/${DB_NAME}
username: ${master_user}
password: ${master_pass}
logLevel: info
vault.addr: ${DBA_VAULT_ADDR}
vault.namespace: ${DBA_VAULT_NAMESPACE}
vault.token: ${DBA_VAULT_TOKEN}

liquibase.liquibaseSchemaName: ${master_user}

liquibase.sqlplus.keep.temp: true
liquibase.sqlplus.keep.temp.name: ${DB_NAME}
liquibase.sqlplus.keep.temp.path: ${WORKSPACE}/oracle/temp